### ISSUE TITLE
Scraping Amazon Reviews by using Amazon Serial Number

### ISSUE THREAD

**Issue by NischalKash** [bsharathramesh/SE_Project1#34]
Description:
To perform sentiment analysis on product reviews, we must provide the link to the reviews page of the product to the application. 

For example: 

Product Review Link:
https://www.amazon.com/product-reviews/B013WC0P2A/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar

Instead of manually navigating to the reviews page of the product, we would like to directly provide the product link instead. 

The reviews can somehow be retrieved by using the Amazon Serial Number (ASN) in the product link. 

Product Link: 
https://www.amazon.com/VicTsing-Wireless-Portable-Receiver-Adjustable/dp/B013WC0P2A?pd_rd_w=9ZKw5&pf_rd_p=c638e3d4-046b-4753-9e53-3752c2d7f6a7&pf_rd_r=DM788J7AD36KTC68MFHH&pd_rd_r=f62b2234-fe33-457f-b904-d98e2cb72d25&pd_rd_wg=fVg6G

Here the ASN is B013WC0P2A

The application needs a feature update where we can pass the product link directly instead of the product reviews link.

Files Involved:
sentimental_analysis/realworld/views.py

Hint: Check the productanalyis method.

**Comment by Hardeepsingh980** [comment]
I think i can do this. I am picking on it.

**Comment by Hardeepsingh980** [comment]
Hello I have created a Pull Request #35. Please have a look. I have also improved other things in this request.

**Comment by mangalvg** [comment]
Great, we will review your pull request. 

We are not sure about merging pull request from forked repository to the original repository. We will confirm with the TA about this.

**Comment by Hardeepsingh980** [comment]
ok. I will like to work on this project as well.

**Comment by mangalvg** [comment]
I discussed with the TA. There is no need to merge your changes to our repository. You just have merge your changes to your forked repository.

**Comment by Hardeepsingh980** [comment]
You are not going to merge my changes to your repo? Are you guys accepting contribution further from outsiders?

**Comment by mangalvg** [comment]
Oh, ok I understand now. 

Sure, we do accept contribution from outsiders. 

This is an academic project for a graduate level course at North Carolina State University and we assumed you were a student in the same course. Sorry for the confusion caused.

Yes, we will review the pull request and merge the changes as soon as possible. 

Thanks a lot for your contribution.

Also we would love to hear back from you. Any suggestions and ideas in improving the project would be most welcome.
