### ISSUE TITLE
Sentiment Analysis and Front end Development.

### ISSUE THREAD

**Issue by bsharathramesh** [bsharathramesh/SE_Project1#4]
## Sentiment Analysis

# Requirements:

**Comment by mangalnathanvg** [comment]
Integrated Sentiment Analysis along with Django setup along with the issue serviced by teammate nischal.

https://github.com/bsharathramesh/SE_Project1/issues/2

**Comment by mangalvg** [comment]
Integrated Sentiment Analysis along with Django setup along with the issue serviced by teammate nischal.

Issue: https://github.com/bsharathramesh/SE_Project1/issues/2

Commit: https://github.com/bsharathramesh/SE_Project1/commit/a76c21b7614230398abcb5b28ebe579aa1fc18b7
