### ISSUE TITLE
Integration of web scraping output and Sentimental analysis tool.

### ISSUE THREAD

**Issue by bsharathramesh** [bsharathramesh/SE_Project1#7]
#7   Integration of web scrapping output and Sentimental analysis tool.

## Output format.
The comment needs to be scrapped from the web page and stored in csv file.
The csv file is fed as input to sentiment analysis.

**Comment by NischalKash** [comment]
Integration Completed Successfully!! Closing this issue now
Reclone or Reopen if issue found again!!
